name: flutter_application_1
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  autocorrect_and_autocomplete_engine: ^0.0.2
  flutter:
    sdk: flutter
  flutter_text_detect_area: ^0.0.2
  image_picker: ^1.1.2
flutter_text_detect_area: ^0.0.2
image_picker: ^1.0.4
autocorrect_and_autocomplete_engine: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
